/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsuccess;

import java.awt.*;
import javax.swing.*;
//import java.awt.Image;
//import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author pc
 */
public class StdAtten extends javax.swing.JFrame {

    /**
     * Creates new form stdAtten
     */
    public StdAtten() {
        initComponents();
        
        dt();
        
        ImageIcon myImage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/attendance.png")));
        
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(attenIcn1.getWidth(), attenIcn1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        
        attenIcn1.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void dt(){
        Date d = new Date();
        
        SimpleDateFormat sdat = new SimpleDateFormat("yyyy-MM-dd");
        
        String dd= sdat.format(d);
         txtAttnDate.setText(dd);
    }
    
    private void reset(){
        txtSbjName.setText("");
        txtTcherName.setText("");
        txtStdID.setText("");
        txtStdID.setText("");
        txtStdName.setText("");
        buttonGroup1.clearSelection();
        txtNotes.setText("");

    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bgPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        attenTitle = new javax.swing.JLabel();
        attenIcn1 = new javax.swing.JLabel();
        attmarkPanl = new javax.swing.JPanel();
        sbjName = new javax.swing.JLabel();
        stdID = new javax.swing.JLabel();
        stdName = new javax.swing.JLabel();
        txtStdID = new javax.swing.JTextField();
        txtStdName = new javax.swing.JTextField();
        presentRB = new javax.swing.JRadioButton();
        absentRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        tchrName = new javax.swing.JLabel();
        txtSbjName = new javax.swing.JTextField();
        txtTcherName = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cnslBtn = new javax.swing.JButton();
        tblPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        attnDate = new javax.swing.JLabel();
        txtAttnDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance");
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        bgPnl.setBackground(new java.awt.Color(153, 204, 255));
        bgPnl.setMaximumSize(new java.awt.Dimension(1000, 580));
        bgPnl.setMinimumSize(new java.awt.Dimension(1000, 580));
        bgPnl.setPreferredSize(new java.awt.Dimension(1000, 580));
        bgPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attenTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        attenTitle.setText("Student Attendace");
        jPanel1.add(attenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 35));
        jPanel1.add(attenIcn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 32, 35));

        bgPnl.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        attmarkPanl.setBackground(new java.awt.Color(198, 228, 255));
        attmarkPanl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 5, new java.awt.Color(102, 102, 102)));

        sbjName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sbjName.setText("Subject Name");

        stdID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        stdID.setText("Student ID");

        stdName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        stdName.setText("Student Name");

        presentRB.setBackground(new java.awt.Color(198, 228, 255));
        buttonGroup1.add(presentRB);
        presentRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        presentRB.setText("Present");
        presentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentRBActionPerformed(evt);
            }
        });

        absentRB.setBackground(new java.awt.Color(198, 228, 255));
        buttonGroup1.add(absentRB);
        absentRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        absentRB.setText("Absent");

        txtNotes.setColumns(20);
        txtNotes.setForeground(new java.awt.Color(153, 153, 153));
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        txtNotes.setText("Special Note");
        txtNotes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNotesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNotesFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtNotes);

        tchrName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tchrName.setText("Teacher's Name");

        createBtn.setBackground(new java.awt.Color(102, 255, 102));
        createBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        createBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-user.png"))); // NOI18N
        createBtn.setText("Save");
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.setIconTextGap(5);

        clearBtn.setBackground(new java.awt.Color(255, 255, 153));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clear.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.setIconTextGap(6);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cnslBtn.setBackground(new java.awt.Color(255, 102, 102));
        cnslBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cnslBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/x.png"))); // NOI18N
        cnslBtn.setText("Cancel");
        cnslBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cnslBtn.setIconTextGap(7);
        cnslBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnslBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attmarkPanlLayout = new javax.swing.GroupLayout(attmarkPanl);
        attmarkPanl.setLayout(attmarkPanlLayout);
        attmarkPanlLayout.setHorizontalGroup(
            attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attmarkPanlLayout.createSequentialGroup()
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attmarkPanlLayout.createSequentialGroup()
                        .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attmarkPanlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sbjName))
                            .addGroup(attmarkPanlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(stdName))
                            .addGroup(attmarkPanlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(stdID))
                            .addGroup(attmarkPanlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tchrName)))
                        .addGap(10, 10, 10)
                        .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTcherName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSbjName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStdName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(attmarkPanlLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cnslBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attmarkPanlLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attmarkPanlLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(presentRB)
                        .addGap(35, 35, 35)
                        .addComponent(absentRB)))
                .addGap(5, 5, 5))
        );
        attmarkPanlLayout.setVerticalGroup(
            attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attmarkPanlLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attmarkPanlLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(sbjName))
                    .addComponent(txtSbjName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTcherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tchrName))
                .addGap(18, 18, 18)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdID))
                .addGap(11, 11, 11)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdName))
                .addGap(11, 11, 11)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(presentRB)
                    .addComponent(absentRB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(attmarkPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnslBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bgPnl.add(attmarkPanl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 370, 410));

        tblPanel.setBackground(new java.awt.Color(153, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Subject Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        javax.swing.GroupLayout tblPanelLayout = new javax.swing.GroupLayout(tblPanel);
        tblPanel.setLayout(tblPanelLayout);
        tblPanelLayout.setHorizontalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        tblPanelLayout.setVerticalGroup(
            tblPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        bgPnl.add(tblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 11, -1, -1));

        attnDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        attnDate.setText("Date :");
        bgPnl.add(attnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 70, 50, 30));
        bgPnl.add(txtAttnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNotesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotesFocusGained
        if(txtNotes.getText().equals("Special Note")){

            txtNotes.setText("");
            txtNotes.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNotesFocusGained

    private void txtNotesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNotesFocusLost
        if(txtNotes.getText().equals("")){

            txtNotes.setText("Special Note");
            txtNotes.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNotesFocusLost

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
        reset();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void presentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentRBActionPerformed

    private void cnslBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnslBtnActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_cnslBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdAtten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdAtten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdAtten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdAtten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StdAtten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton absentRB;
    private javax.swing.JLabel attenIcn1;
    private javax.swing.JLabel attenTitle;
    private javax.swing.JPanel attmarkPanl;
    private javax.swing.JLabel attnDate;
    private javax.swing.JPanel bgPnl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton cnslBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton presentRB;
    private javax.swing.JLabel sbjName;
    private javax.swing.JLabel stdID;
    private javax.swing.JLabel stdName;
    private javax.swing.JPanel tblPanel;
    private javax.swing.JLabel tchrName;
    private javax.swing.JTextField txtAttnDate;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtSbjName;
    private javax.swing.JTextField txtStdID;
    private javax.swing.JTextField txtStdName;
    private javax.swing.JTextField txtTcherName;
    // End of variables declaration//GEN-END:variables
}
